import '../styles/globals.css';
import Navbar from './components/Navbar';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}
 
export default function RootLayout({ children }) {
 return (
    <html lang="en">
      <body>
        <header>
          <Navbar/>
        </header>
        <main>
          {children}
        </main>
      </body>
    </html>
  )
}
